services:
  db:
    image: postgres:latest
    container_name: postgres_fazenda
    environment:
      - POSTGRES_USER=brunavaloes
      - POSTGRES_DB=stardew
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    volumes:
      - stardew_data:/var/lib/postgresql/data

volumes:
  stardew_data: